
/*===============================================================================
 *
 *      Code Comment Block Here.
 *      
 *      Generated by Code Generator on 28/07/2015 12:13  
 * 
 *===============================================================================
 */

namespace FeatureDemandPlanning.Model
{
    public class ConfigurationItem : BusinessObject
    {
        public string ConfigurationKey { get; set; }
        public string Value { get; set; }
        public string Description { get; set; }
        public string DataType { get; set; }

        // A blank constructor
        public ConfigurationItem() { ;}
    }
}