
/*===============================================================================
 *
 *      Code Comment Block Here.
 *      
 *      Generated by Code Generator on 28/07/2015 12:14  
 * 
 *===============================================================================
 */

namespace FeatureDemandPlanning.Model
{
    public class ForecastComparison : BusinessObject
    {
        public int ForecastComparisonId { get; set; }
        public int ForecastId { get; set; }
        public int ForecastVehicleId { get; set; }
        public int SortOrder { get; set; }
        public bool IsActive { get; set; }

        // A blank constructor
        public ForecastComparison() { ;}
    }
}