
/*===============================================================================
 *
 *      Code Comment Block Here.
 *      
 *      Generated by Code Generator on 23/07/2014 11:43  
 * 
 *===============================================================================
 */

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Data;
using OXO.Dapper;

namespace OXO.BusinessObjects
{
    public class OXODocChangeLog : BusinessObject
    {
        private string _updatedBy;  

        public int ProcessUID { get; set; } 
        public int OXODocId { get; set; }
        public string Section { get; set; }
        public string Reason { get; set; }
        public string Note { get; set; }
        public string PACNRef { get; set; }
        public string PDLRef { get; set; }
        public string ETrackerRef { get; set; }

        public new string UpdatedBy
        {
            get { return _updatedBy; }
            set { _updatedBy = value; }
        }

        public new string LastUpdated
        {
            get {

                if (base.LastUpdated.HasValue)
                    return base.LastUpdated.Value.ToString("yyyy-MM-dd HH:mm");
                else
                    return "";
            }
        }

        public OXODataItem[] DataItem  { get; set; }

        // A blank constructor
        public OXODocChangeLog() {;}
    }

    public class OXODocChangeLogDetail : BusinessObject
    {
        public int ProcessUID { get; set; }
        public string MarketName { get; set; }
        public string ModelName { get; set; }
        public string FeatureName { get; set; }
        public string PrevFitment { get; set; }
        public string CurrFitment { get; set; }

        // A blank constructor
        public OXODocChangeLogDetail() { ;}
    }

}