
/*===============================================================================
 *
 *      Code Comment Block Here.
 *      
 *      Generated by Code Generator on 28/07/2015 12:15  
 * 
 *===============================================================================
 */

namespace FeatureDemandPlanning.Model
{
    public class PermissionOperation : BusinessObject
    {
            public int FdpPermissionOperationId { get; set; }
            public string FdpPermissionObjectType { get; set; }
            public string Operation { get; set; }
            public string Description { get; set; }
           
        // A blank constructor
        public PermissionOperation() {;}
    }
}