
/*===============================================================================
 *
 *      Code Comment Block Here.
 *      
 *      Generated by Code Generator on 28/07/2015 12:14  
 * 
 *===============================================================================
 */

namespace FeatureDemandPlanning.Model
{
    public class PermissionObjectType : BusinessObject
    {
        public int Id { get; set; } 
            public string FdpPermissionObjectType { get; set; }
            public string Description { get; set; }
           
        // A blank constructor
        public PermissionObjectType() {;}
    }
}