
/*===============================================================================
 *
 *      Code Comment Block Here.
 *      
 *      Generated by Code Generator on 28/07/2015 12:15  
 * 
 *===============================================================================
 */

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Data;
using FeatureDemandPlanning.Model.Dapper;

namespace FeatureDemandPlanning.Model
{
    public class PermissionOperation : BusinessObject
    {
        public int Id { get; set; } 
            public int FdpPermissionOperationId { get; set; }
            public string FdpPermissionObjectType { get; set; }
            public string Operation { get; set; }
            public string Description { get; set; }
           
        // A blank constructor
        public PermissionOperation() {;}
    }
}