//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FeatureDemandPlanning.Model.RADSMailService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://jlrint.com/rads/message/sendmail/1", ConfigurationName="RADSMailService.SendMailSoap")]
    public interface SendMailSoap {
        
        // CODEGEN: Generating message contract since message SendMailRequestWithAttachmentsRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://jlrint.com/rads/message/sendmail/1/SendMailRequestWithAttachments", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FeatureDemandPlanning.Model.RADSMailService.SendMailRequestWithAttachmentsResponse SendMailRequestWithAttachments(FeatureDemandPlanning.Model.RADSMailService.SendMailRequestWithAttachmentsRequest request);
        
        // CODEGEN: Generating message contract since message SendMailRequestRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://jlrint.com/rads/message/sendmail/1/SendMailRequest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FeatureDemandPlanning.Model.RADSMailService.SendMailRequestResponse SendMailRequest(FeatureDemandPlanning.Model.RADSMailService.SendMailRequestRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://jlrint.com/rads/message/sendmail/1")]
    public partial class JLRCommonHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string contextIdField;
        
        private string timestampField;
        
        private string toField;
        
        private string fromField;
        
        private string loggingField;
        
        private string messageIDField;
        
        private string nullMessageField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ContextId {
            get {
                return this.contextIdField;
            }
            set {
                this.contextIdField = value;
                this.RaisePropertyChanged("ContextId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Timestamp {
            get {
                return this.timestampField;
            }
            set {
                this.timestampField = value;
                this.RaisePropertyChanged("Timestamp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string To {
            get {
                return this.toField;
            }
            set {
                this.toField = value;
                this.RaisePropertyChanged("To");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string From {
            get {
                return this.fromField;
            }
            set {
                this.fromField = value;
                this.RaisePropertyChanged("From");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Logging {
            get {
                return this.loggingField;
            }
            set {
                this.loggingField = value;
                this.RaisePropertyChanged("Logging");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string MessageID {
            get {
                return this.messageIDField;
            }
            set {
                this.messageIDField = value;
                this.RaisePropertyChanged("MessageID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string NullMessage {
            get {
                return this.nullMessageField;
            }
            set {
                this.nullMessageField = value;
                this.RaisePropertyChanged("NullMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://jlrint.com/rads/message/sendmail/1")]
    public partial class AuthHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string userNameField;
        
        private string passwordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
                this.RaisePropertyChanged("UserName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendMailRequestWithAttachments", WrapperNamespace="http://jlrint.com/rads/message/sendmail/1", IsWrapped=true)]
    public partial class SendMailRequestWithAttachmentsRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://jlrint.com/rads/message/sendmail/1")]
        public FeatureDemandPlanning.Model.RADSMailService.JLRCommonHeader JLRCommonHeader;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://jlrint.com/rads/message/sendmail/1")]
        public FeatureDemandPlanning.Model.RADSMailService.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://jlrint.com/rads/message/sendmail/1", Order=0)]
        public string from;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://jlrint.com/rads/message/sendmail/1", Order=1)]
        public string to;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://jlrint.com/rads/message/sendmail/1", Order=2)]
        public string subject;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://jlrint.com/rads/message/sendmail/1", Order=3)]
        public string body;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://jlrint.com/rads/message/sendmail/1", Order=4)]
        public string cc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://jlrint.com/rads/message/sendmail/1", Order=5)]
        public string bcc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://jlrint.com/rads/message/sendmail/1", Order=6)]
        public string app;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://jlrint.com/rads/message/sendmail/1", Order=7)]
        public string attachments;
        
        public SendMailRequestWithAttachmentsRequest() {
        }
        
        public SendMailRequestWithAttachmentsRequest(FeatureDemandPlanning.Model.RADSMailService.JLRCommonHeader JLRCommonHeader, FeatureDemandPlanning.Model.RADSMailService.AuthHeader AuthHeader, string from, string to, string subject, string body, string cc, string bcc, string app, string attachments) {
            this.JLRCommonHeader = JLRCommonHeader;
            this.AuthHeader = AuthHeader;
            this.from = from;
            this.to = to;
            this.subject = subject;
            this.body = body;
            this.cc = cc;
            this.bcc = bcc;
            this.app = app;
            this.attachments = attachments;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendMailRequestWithAttachmentsResponse", WrapperNamespace="http://jlrint.com/rads/message/sendmail/1", IsWrapped=true)]
    public partial class SendMailRequestWithAttachmentsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://jlrint.com/rads/message/sendmail/1", Order=0)]
        public string SendMailRequestWithAttachmentsResult;
        
        public SendMailRequestWithAttachmentsResponse() {
        }
        
        public SendMailRequestWithAttachmentsResponse(string SendMailRequestWithAttachmentsResult) {
            this.SendMailRequestWithAttachmentsResult = SendMailRequestWithAttachmentsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendMailRequest", WrapperNamespace="http://jlrint.com/rads/message/sendmail/1", IsWrapped=true)]
    public partial class SendMailRequestRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://jlrint.com/rads/message/sendmail/1")]
        public FeatureDemandPlanning.Model.RADSMailService.JLRCommonHeader JLRCommonHeader;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://jlrint.com/rads/message/sendmail/1")]
        public FeatureDemandPlanning.Model.RADSMailService.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://jlrint.com/rads/message/sendmail/1", Order=0)]
        public string from;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://jlrint.com/rads/message/sendmail/1", Order=1)]
        public string to;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://jlrint.com/rads/message/sendmail/1", Order=2)]
        public string subject;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://jlrint.com/rads/message/sendmail/1", Order=3)]
        public string body;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://jlrint.com/rads/message/sendmail/1", Order=4)]
        public string cc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://jlrint.com/rads/message/sendmail/1", Order=5)]
        public string bcc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://jlrint.com/rads/message/sendmail/1", Order=6)]
        public string app;
        
        public SendMailRequestRequest() {
        }
        
        public SendMailRequestRequest(FeatureDemandPlanning.Model.RADSMailService.JLRCommonHeader JLRCommonHeader, FeatureDemandPlanning.Model.RADSMailService.AuthHeader AuthHeader, string from, string to, string subject, string body, string cc, string bcc, string app) {
            this.JLRCommonHeader = JLRCommonHeader;
            this.AuthHeader = AuthHeader;
            this.from = from;
            this.to = to;
            this.subject = subject;
            this.body = body;
            this.cc = cc;
            this.bcc = bcc;
            this.app = app;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendMailRequestResponse", WrapperNamespace="http://jlrint.com/rads/message/sendmail/1", IsWrapped=true)]
    public partial class SendMailRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://jlrint.com/rads/message/sendmail/1", Order=0)]
        public string SendMailRequestResult;
        
        public SendMailRequestResponse() {
        }
        
        public SendMailRequestResponse(string SendMailRequestResult) {
            this.SendMailRequestResult = SendMailRequestResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SendMailSoapChannel : FeatureDemandPlanning.Model.RADSMailService.SendMailSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SendMailSoapClient : System.ServiceModel.ClientBase<FeatureDemandPlanning.Model.RADSMailService.SendMailSoap>, FeatureDemandPlanning.Model.RADSMailService.SendMailSoap {
        
        public SendMailSoapClient() {
        }
        
        public SendMailSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SendMailSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SendMailSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SendMailSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FeatureDemandPlanning.Model.RADSMailService.SendMailRequestWithAttachmentsResponse FeatureDemandPlanning.Model.RADSMailService.SendMailSoap.SendMailRequestWithAttachments(FeatureDemandPlanning.Model.RADSMailService.SendMailRequestWithAttachmentsRequest request) {
            return base.Channel.SendMailRequestWithAttachments(request);
        }
        
        public string SendMailRequestWithAttachments(FeatureDemandPlanning.Model.RADSMailService.JLRCommonHeader JLRCommonHeader, FeatureDemandPlanning.Model.RADSMailService.AuthHeader AuthHeader, string from, string to, string subject, string body, string cc, string bcc, string app, string attachments) {
            FeatureDemandPlanning.Model.RADSMailService.SendMailRequestWithAttachmentsRequest inValue = new FeatureDemandPlanning.Model.RADSMailService.SendMailRequestWithAttachmentsRequest();
            inValue.JLRCommonHeader = JLRCommonHeader;
            inValue.AuthHeader = AuthHeader;
            inValue.from = from;
            inValue.to = to;
            inValue.subject = subject;
            inValue.body = body;
            inValue.cc = cc;
            inValue.bcc = bcc;
            inValue.app = app;
            inValue.attachments = attachments;
            FeatureDemandPlanning.Model.RADSMailService.SendMailRequestWithAttachmentsResponse retVal = ((FeatureDemandPlanning.Model.RADSMailService.SendMailSoap)(this)).SendMailRequestWithAttachments(inValue);
            return retVal.SendMailRequestWithAttachmentsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FeatureDemandPlanning.Model.RADSMailService.SendMailRequestResponse FeatureDemandPlanning.Model.RADSMailService.SendMailSoap.SendMailRequest(FeatureDemandPlanning.Model.RADSMailService.SendMailRequestRequest request) {
            return base.Channel.SendMailRequest(request);
        }
        
        public string SendMailRequest(FeatureDemandPlanning.Model.RADSMailService.JLRCommonHeader JLRCommonHeader, FeatureDemandPlanning.Model.RADSMailService.AuthHeader AuthHeader, string from, string to, string subject, string body, string cc, string bcc, string app) {
            FeatureDemandPlanning.Model.RADSMailService.SendMailRequestRequest inValue = new FeatureDemandPlanning.Model.RADSMailService.SendMailRequestRequest();
            inValue.JLRCommonHeader = JLRCommonHeader;
            inValue.AuthHeader = AuthHeader;
            inValue.from = from;
            inValue.to = to;
            inValue.subject = subject;
            inValue.body = body;
            inValue.cc = cc;
            inValue.bcc = bcc;
            inValue.app = app;
            FeatureDemandPlanning.Model.RADSMailService.SendMailRequestResponse retVal = ((FeatureDemandPlanning.Model.RADSMailService.SendMailSoap)(this)).SendMailRequest(inValue);
            return retVal.SendMailRequestResult;
        }
    }
}
