
/*===============================================================================
 *
 *      Code Comment Block Here.
 *      
 *      Generated by Code Generator on 28/07/2014 15:00  
 * 
 *===============================================================================
 */

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Data;
using FeatureDemandPlanning.Dapper;

namespace FeatureDemandPlanning.BusinessObjects
{
    public class Permission : BusinessObject
    {
        public string CDSID { get; set; }
        public string ObjectType { get; set; }
        public int? ObjectId { get; set; }
        public string ObjectVal { get; set; }
        public string Operation { get; set; }
           
        // A blank constructor
        public Permission() {;}

        public bool CanEdit
        {
            get { return Operation == "CanEdit"; }
        }

        public bool CanView
        {
            get { return Operation == "CanEdit" || Operation == "CanView"; }
        }
        

    }
}