
/*===============================================================================
 *
 *      Code Comment Block Here.
 *      
 *      Generated by Code Generator on 27/05/2014 16:01  
 * 
 *===============================================================================
 */

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Data;
using FeatureDemandPlanning.Dapper;

namespace FeatureDemandPlanning.BusinessObjects
{
    public class ReferenceList: BusinessObject
    {
        public string Code { get; set; }
        public string Description { get; set; }
        public string ListName { get; set; }
        public int DisplayOrder { get; set; }
        public bool Active { get; set; }
           
        // A blank constructor
        public ReferenceList() {;}
    }
}