
/*===============================================================================
 *
 *      Code Comment Block Here.
 *      
 *      Generated by Code Generator on 28/07/2015 12:14  
 * 
 *===============================================================================
 */

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Data;
using FeatureDemandPlanning.Dapper;

namespace FeatureDemandPlanning.BusinessObjects
{
    public class PermissionObjectType : BusinessObject
    {
        public int Id { get; set; } 
            public string FdpPermissionObjectType { get; set; }
            public string Description { get; set; }
           
        // A blank constructor
        public PermissionObjectType() {;}
    }
}