CREATE TABLE [dbo].[TMP_Feature_Import] (
    [Feat_Code]         NVARCHAR (MAX) NULL,
    [OA_Code]           NVARCHAR (MAX) NULL,
    [Feat_Desc]         NVARCHAR (MAX) NULL,
    [Priorty_X351_L462] NVARCHAR (MAX) NULL,
    [In_LR_Coding]      NVARCHAR (MAX) NULL,
    [In_Jag_Coding]     NVARCHAR (MAX) NULL,
    [WERS_Code]         NVARCHAR (MAX) NULL,
    [RADS_Id]           NVARCHAR (MAX) NULL,
    [On_Relevant_Map]   NVARCHAR (MAX) NULL,
    [Brand_Desc_LR]     NVARCHAR (MAX) NULL,
    [LR_Char]           NVARCHAR (MAX) NULL,
    [LR_Verified_By]    NVARCHAR (MAX) NULL,
    [Brand_Desc_Jag]    NVARCHAR (MAX) NULL,
    [Jag_Char]          NVARCHAR (MAX) NULL,
    [Jag_Verified_By]   NVARCHAR (MAX) NULL,
    [JLR_OXO_Grp]       NVARCHAR (MAX) NULL,
    [Grp_Verified_By]   NVARCHAR (MAX) NULL,
    [EFG_Code]          NVARCHAR (MAX) NULL,
    [EFG_Type]          NVARCHAR (MAX) NULL,
    [EFG_Desc]          NVARCHAR (MAX) NULL,
    [Long_Desc]         NVARCHAR (MAX) NULL,
    [Legal_Comments]    NVARCHAR (MAX) NULL,
    [Config_Grp]        NVARCHAR (MAX) NULL,
    [X761]              NVARCHAR (MAX) NULL,
    [X760]              NVARCHAR (MAX) NULL,
    [X152]              NVARCHAR (MAX) NULL,
    [X351]              NVARCHAR (MAX) NULL,
    [X260]              NVARCHAR (MAX) NULL,
    [X360]              NVARCHAR (MAX) NULL,
    [X540]              NVARCHAR (MAX) NULL,
    [L405]              NVARCHAR (MAX) NULL,
    [L494]              NVARCHAR (MAX) NULL,
    [L538]              NVARCHAR (MAX) NULL,
    [L319]              NVARCHAR (MAX) NULL,
    [L550]              NVARCHAR (MAX) NULL,
    [L462]              NVARCHAR (MAX) NULL,
    [L316]              NVARCHAR (MAX) NULL,
    [L663]              NVARCHAR (MAX) NULL,
    [L560]              NVARCHAR (MAX) NULL,
    [X590]              NVARCHAR (MAX) NULL,
    [X261]              NVARCHAR (MAX) NULL,
    [Status]            NVARCHAR (MAX) NULL
);



