
/*===============================================================================
 *
 *      Code Comment Block Here.
 *      
 *      Generated by Code Generator on 28/07/2015 12:14  
 * 
 *===============================================================================
 */

using System;
using System.Collections.Generic;
using System.Linq;
using System.Data;
using FeatureDemandPlanning.Model.Dapper;
using FeatureDemandPlanning.Model;
using FeatureDemandPlanning.Model.Helpers;
using FeatureDemandPlanning.Model.Interfaces;
using System.Data.SqlClient;
using FeatureDemandPlanning.Model.Context;
using FeatureDemandPlanning.Model.Filters;

namespace FeatureDemandPlanning.DataStore
{
	public class ForecastDataStore: DataStoreBase
	{
	
		public ForecastDataStore(string cdsid)
		{
			CurrentCDSID = cdsid;
		}

        public PagedResults<ForecastSummary> ForecastGetMany(ForecastFilter filter)
        {
            PagedResults<ForecastSummary> retVal;

            using (var conn = DbHelper.GetDBConnection())
            {
                try
                {
                    var para = new DynamicParameters();
                    var totalRecords = 0;
                    var totalDisplayRecords = 0;

                    if (filter.ForecastId.HasValue)
                    {
                        para.Add("@ForecastId", filter.ForecastId.Value, DbType.Int32);
                    }
                    if (!string.IsNullOrEmpty(filter.FilterMessage))
                    {
                        para.Add("@FilterMessage", filter.FilterMessage, DbType.String, size: 50);
                    }
                    if (filter.PageIndex.HasValue)
                    {
                        para.Add("@PageIndex", filter.PageIndex.Value, DbType.Int32);
                    }
                    if (filter.PageSize.HasValue)
                    {
                        para.Add("@PageSize", filter.PageSize.Value, DbType.Int32);
                    }
                    if (filter.SortIndex.HasValue)
                    {
                        para.Add("@SortIndex", filter.SortIndex.Value, DbType.Int32);
                    }
                    if (filter.SortDirection != Model.Enumerations.SortDirection.NotSet)
                    {
                        var direction = filter.SortDirection == Model.Enumerations.SortDirection.Descending ? "DESC" : "ASC";
                        para.Add("@SortDirection", direction, DbType.String);
                    }

                    // TODO implement the CDSId to get only those forecasts the user has permissions for
                    para.Add("@CDSId", CurrentCDSID, DbType.String);
                    para.Add("@TotalPages", dbType: DbType.Int32, direction: ParameterDirection.Output);
                    para.Add("@TotalRecords", dbType: DbType.Int32, direction: ParameterDirection.Output);
                    para.Add("@TotalDisplayRecords", dbType: DbType.Int32, direction: ParameterDirection.Output);

                    var results = conn.Query<ForecastSummary>("dbo.Fdp_Forecast_GetMany", para, commandType: CommandType.StoredProcedure);

                    var forecastSummaries = results as IList<ForecastSummary> ?? results.ToList();
                    if (forecastSummaries.Any())
                    {
                        totalRecords = para.Get<int>("@TotalRecords");
                        totalDisplayRecords = para.Get<int>("@TotalDisplayRecords");
                    }
                    retVal = new PagedResults<ForecastSummary>()
                    {
                        PageIndex = filter.PageIndex ?? 1,
                        TotalRecords = totalRecords,
                        TotalDisplayRecords = totalDisplayRecords,
                        PageSize = filter.PageSize ?? totalRecords
                    };

                    var currentPage = new List<ForecastSummary>();
                    foreach (var result in forecastSummaries)
                    {
                        currentPage.Add(result);
                    }

                    retVal.CurrentPage = currentPage;
                }
                catch (Exception ex)
                {
                    AppHelper.LogError("ForecastDataStore.ForecastGetMany", ex.Message, CurrentCDSID);
                    throw;
                }
            }

            return retVal;
        }

        public IForecast ForecastGet(int id)
        {
            Forecast forecast;

            using (var conn = DbHelper.GetDBConnection())
            {
                try
                {
                    var para = new DynamicParameters();
                    para.Add("@ForecastId", id, DbType.Int32);

                    var results = conn.QueryMultiple("dbo.Fdp_Forecast_Get", para, commandType: CommandType.StoredProcedure);

                    // First resultset represents basic forecast information

                    forecast = results.Read<Forecast>().FirstOrDefault();

                    // Second resultset represents the forecast vehicle

                    if (forecast != null)
                    {
                        forecast.ForecastVehicle = results.Read<Vehicle>().FirstOrDefault();
                    }

                    // Final resultset represents the comparison vehicles

                    if (forecast != null)
                    {
                        forecast.ComparisonVehicles = results.Read<Vehicle>();
                    }
                }
                catch (Exception ex)
                {
                    AppHelper.LogError("ForecastDataStore.ForecastGet", ex.Message, CurrentCDSID);
                    throw;
                }
            }

            return forecast;
        }
		//public Forecast ForecastTrimMappingGet(int forecastId)
		//{
		//    using (IDbConnection conn = DbHelper.GetDBConnection())
		//    {
		//        try
		//        {
		//            var para = new DynamicParameters();
		//            para.Add("@ForecastId", forecastId, dbType: DbType.Int32);

		//            var results = conn.QueryMultiple("dbo.Fdp_ForecastMappedTrim_Get", para, commandType: CommandType.StoredProcedure);

		//            // First resultset represents forecast vehicle trim information

		//            forecast = results.Read<Forecast>().FirstOrDefault();

		//            // Second resultset represents the comparison vehicles trim and any mapping information

		//            if (forecast != null)
		//            {
		//                forecast.ForecastVehicle = results.Read<Vehicle>().FirstOrDefault();
		//            }

		//            // Final resultset represents the comparison vehicles

		//            if (forecast != null)
		//            {
		//                forecast.ComparisonVehicles = results.Read<Vehicle>();
		//            }
		//        }
		//        catch (Exception ex)
		//        {
		//            AppHelper.LogError("ForecastDataStore.ForecastGet", ex.Message, CurrentCDSID);
		//            throw;
		//        }
		//    }
		//}

		public IForecast ForecastSave(IForecast forecastToSave)
		{
			try
			{
				using (var connection = DbHelper.GetDBConnection())
				{
					var para = new DynamicParameters();

					para.Add("@ForecastId", forecastToSave.ForecastId, DbType.Int32, ParameterDirection.InputOutput);
					para.Add("@SystemUser", CurrentCDSID, DbType.String, size: 16);
					para.Add("@ProgrammeId", forecastToSave.ForecastVehicle.ProgrammeId, DbType.Int32);
					para.Add("@Gateway", forecastToSave.ForecastVehicle.Gateway, DbType.String, size: 50);

					var trans = connection.BeginTransaction();

					connection.Execute("Fdp_Forecast_Save", para, commandType: CommandType.StoredProcedure, transaction: trans);

					if (!forecastToSave.ForecastId.HasValue)
					{
						forecastToSave.ForecastId = para.Get<int>("@ForecastId");
					}

                    ForecastComparisonVehiclesSave(forecastToSave, connection, trans);
                    ForecastComparisonTrimSave(forecastToSave, connection, trans);

					trans.Commit();
				}
			}
            catch (SqlException sqex)
            {
                AppHelper.LogError("ForecastDataStore.ForecastSave", sqex.Message, CurrentCDSID);
                throw new ApplicationException("Database store error", sqex);
            }
            catch (ApplicationException ex)
            {
                AppHelper.LogError("ForecastDataStore.ForecastSave", ex.Message, CurrentCDSID);
                throw;
            }

			return forecastToSave;
		}

        public void ForecastComparisonVehiclesSave( IForecast forecastToSave,
                                                    IDbConnection connection,
												    IDbTransaction transaction)
        {
            var vehicleIndex = 1;
            foreach (var comparisonVehicle in forecastToSave.ComparisonVehicles)
            {
                ForecastComparisonVehicleSave(forecastToSave, comparisonVehicle, connection, transaction, vehicleIndex++);
            }
        }

        public void ForecastComparisonTrimSave( IForecast forecastToSave,
                                                IDbConnection connection,
												IDbTransaction transaction)
        {
            //foreach (var mapping in forecastToSave.TrimMappings)
            //{
            //    if (mapping.ComparisonVehicleTrimId.HasValue)
            //    {
            //        ForecastComparisonTrimSave(forecastToSave, mapping, connection, transaction);
            //    }
            //    else
            //    {
            //        ForecastComparisonTrimDelete(forecastToSave, mapping, connection, transaction);
            //    }
            //}
        }

        public void ForecastComparisonTrimSave( IForecast forecastToSave, 
												ForecastTrimMapping mappingToSave,
												IDbConnection connection,
												IDbTransaction transaction)
        {
            using (DbHelper.GetDBConnection())
            {
                try
                {
                    var para = new DynamicParameters();
                    para.Add("@ForecastId", forecastToSave.ForecastId, DbType.Int32);
                    para.Add("@SystemUser", CurrentCDSID, DbType.String, size: 16);
                    //para.Add("@ForecastVehicleTrimId", mappingToSave.ForecastVehicleTrimId, dbType: DbType.Int32);
                    //para.Add("@ComparisonVehicleProgrammeId", mappingToSave.ComparisonVehicleProgrammeId, dbType: DbType.Int32);
                    //para.Add("@ComparisonVehicleTrimId", mappingToSave.ComparisonVehicleTrimId.Value, dbType: DbType.Int32);
                    para.Add("@ForecastComparisonTrimId", null, DbType.Int32, ParameterDirection.Output);

                    connection.Execute("Fdp_ForecastComparisonTrim_Save", para, commandType: CommandType.StoredProcedure, transaction: transaction);

                    //if (!mappingToSave.Id.HasValue)
                    //{
                    //    mappingToSave.Id = para.Get<int>("@ForecastComparisonTrimId");
                    //}
                }
                catch (SqlException sqex)
                {
                    AppHelper.LogError("ForecastDataStore.ForecastComparisonTrimSave", sqex.Message, CurrentCDSID);
                    throw new ApplicationException("Data store error", sqex);
                }
                catch (ApplicationException ex)
                {
                    AppHelper.LogError("ForecastDataStore.ForecastComparisonTrimSave", ex.Message, CurrentCDSID);
                    throw;
                }
            }
        }

	    public void ForecastComparisonTrimDelete(   IForecast forecastToSave, 
												    ForecastTrimMapping mappingToDelete,
												    IDbConnection connection,
												    IDbTransaction transaction)
        {
            using (var conn = DbHelper.GetDBConnection())
            {
                try
                {
                    var para = new DynamicParameters();
                    para.Add("@ForecastId", forecastToSave.ForecastId, DbType.Int32);
                    para.Add("@SystemUser", CurrentCDSID, DbType.String, size: 16);
                    //para.Add("@ForecastVehicleTrimId", mappingToDelete.ForecastVehicleTrimId, dbType: DbType.Int32);
                    //para.Add("@ComparisonVehicleProgrammeId", mappingToDelete.ComparisonVehicleProgrammeId, dbType: DbType.Int32);

                    connection.Execute("Fdp_ForecastComparisonTrim_Delete", para, commandType: CommandType.StoredProcedure, transaction: transaction);
                }
                catch (Exception ex)
                {
                    AppHelper.LogError("ForecastDataStore.ForecastComparisonTrimDelete", ex.Message, CurrentCDSID);
                    throw;
                }
            }
        }

		public void ForecastComparisonVehicleSave(  IForecast forecastToSave, 
												    IVehicle vehicleToSave,
												    IDbConnection connection,
												    IDbTransaction transaction,
												    int vehicleIndex)
		{
			using (var conn = DbHelper.GetDBConnection())
			{
				try
				{
				    var para = new DynamicParameters();
					para.Add("@ForecastId", forecastToSave.ForecastId, DbType.Int32);
					para.Add("@SystemUser", CurrentCDSID, DbType.String, size: 16);
					para.Add("@ProgrammeId", vehicleToSave.ProgrammeId, DbType.Int32);
					para.Add("@VehicleIndex", vehicleIndex, DbType.Int32);
                    para.Add("@ForecastComparisonId", null, DbType.Int32, ParameterDirection.Output);

					connection.Execute("Fdp_ForecastComparisonVehicle_Save", para, commandType: CommandType.StoredProcedure, transaction: transaction);

                    para.Get<int>("@ForecastComparisonId");
				}
                catch (SqlException sqex)
                {
                    AppHelper.LogError("ForecastDataStore.ForecastComparisonVehicleSave", sqex.Message, CurrentCDSID);
                    throw new ApplicationException("Data store error", sqex);
                }
				catch (ApplicationException ex)
				{
					AppHelper.LogError("ForecastDataStore.ForecastComparisonVehicleSave", ex.Message, CurrentCDSID);
					throw;
				}
			}
		}

		public bool ForecastDelete(int id)
		{
			var retVal = true;
			
			using (DbHelper.GetDBConnection())
			{
			    try
			    {
			        var para = new DynamicParameters();
			        para.Add("@ForecastId", id, DbType.Int32);
			        para.Add("@SystemUser", CurrentCDSID, DbType.String, size: 16);               
			    }
			    catch (Exception ex)
			    {
			        AppHelper.LogError("ForecastDataStore.ForecastDelete", ex.Message, CurrentCDSID);
			        retVal = false;
			    }
			}

			return retVal;
		}

        public IEnumerable<ForecastTrimMapping> TrimMappingGetMany(int forecastId)
        {
            IEnumerable<ForecastTrimMapping> retVal = null;
            using (var conn = DbHelper.GetDBConnection())
            {
                try
                {
                    var para = new DynamicParameters();
                    para.Add("@ForecastId", forecastId, DbType.Int32);

                    retVal = conn.Query<ForecastTrimMapping>("dbo.Fdp_ForecastComparisonTrim_GetMany", para, commandType: CommandType.StoredProcedure);
                }
                catch (Exception ex)
                {
                    AppHelper.LogError("ForecastDataStore.TrimMappingGetMany", ex.Message, CurrentCDSID);
                }
            }

            return retVal;   
        }
    }
}